name: Build ESAPI Script - v18.0

on:
  workflow_dispatch:
    inputs:
      dateInput:
        description: 'Expiration Date'
        required: true
        default: '6/1/2025'

jobs:
  build:
    runs-on: windows-2019
    env:
      GITHUB_WORKSPACE_PACKAGES_PATH: ..\packages\ESAPI.18.0.0.1\lib\net48\
      PROJECT_NAME: MAAS-SFRThelper
      PROJECT_ROOT: ${{ github.workspace }}/MAAS-SFRThelper
      CSPROJ_FILE_NAME: MAAS-SFRThelper.csproj
      SOLUTION_NAME: MAAS-SFRThelper.sln
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Get Current Date
      id: currentDate
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "MM/DD/YYYY"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Update AssemblyInfo.cs
      id: update_assembly_info
      run: |
        .\.github\workflows\Update-AssemblyInfo.ps1 `
          -AssemblyInfoFilePath ${{ env.PROJECT_ROOT }}/Properties/AssemblyInfo.cs `
          -ExpirationDate "${{ github.event.inputs.dateInput }}" `
          -BuildNumber ${{ env.BUILD_NUMBER }} `
          -ProjectName ${{ env.PROJECT_NAME }}

    - name: Update Target Framework Version to 4.8
      uses: Nambers/ReplaceStringInFile@v1.1
      with:
        path: ${{ env.PROJECT_ROOT }}/${{ env.CSPROJ_FILE_NAME }}
        oldString: "TargetFrameworkVersion>v[\\d\\.]+<"
        newString: 'TargetFrameworkVersion>v4.8<'
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Download nuget packages
      run: nuget install ${{ env.PROJECT_ROOT }}/packages.config -OutputDirectory packages

    - name: Add VIC GitHub NuGet repository
      run: nuget source add `
        -Name github `
        -Source "https://nuget.pkg.github.com/Varian-MedicalAffairsAppliedSolutions/index.json" `
        -UserName craman96 `
        -Password ${{ secrets.GITHUB_TOKEN }} `
        -StorePasswordInClearText

    - name: Download internal ESAPI nuget package
      run: nuget install ESAPI -Version 18.0.0.1 -OutputDirectory packages

    - name: Update hint paths in the csproj file
      run: |
        .\.github\workflows\Update-EsapiHintPaths.ps1 `
        -CsprojFilePath ${{ env.PROJECT_ROOT }} `
        -CsprojFileName ${{ env.CSPROJ_FILE_NAME }}

    - name: Build Solution
      run: msbuild.exe ${{ env.SOLUTION_NAME }} /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="x64" /p:configuration="Release"
        
    - name: Zip
      id: zip_release
      run: |
        $normalizedFilePath = "${{ github.workspace }}/V18.0-${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}.zip" -replace '\\', '/'
        
        Get-ChildItem -Path "${{ env.PROJECT_ROOT }}\bin\x64\Release\*" -Recurse |
          Compress-Archive -DestinationPath $normalizedFilePath
        
        "NORMALIZED_FILE_PATH=$($normalizedFilePath)" >> $env:GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV18.0
        tag_name: ${{env.PROJECT_NAME}}${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV18.0
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body: |
          This is an official release of the **`${{ env.PROJECT_NAME }}`** project.
          Supported Eclipse version: `V18.0`.
          The generated dll is valid until `${{ github.event.inputs.dateInput }}`, and generated on `${{ steps.currentDate.outputs.time }}`.
        files: ${{ steps.zip_release.outputs.NORMALIZED_FILE_PATH }}
